using System;
using System.Collections.Generic;

namespace oracleofages;
public enum TreasureVariable
{
    ShortSecretIndex,
    DummyC608,
    AnimalCompanion,
    RememberedCompanionId,
    Bombchus,
    LinkHealth,
    LinkMaxHealth,
    HeartPieces,
    Rupees,
    ShieldLevel,
    Bombs,
    SwordLevel,
    SeedSatchelLevel,
    SwitchHookLevel,
    SelectedHarpSong,
    BraceletLevel,
    EmberSeeds,
    ScentSeeds,
    PegasusSeeds,
    GaleSeeds,
    MysterySeeds,
    GashaSeeds,
    EssencesObtained,
    TradeItem,
    TuniNutState,
    Slates,
    RingBoxLevel,
    UnappraisedRings,
    DungeonSmallKeys,
    DungeonBossKeys,
    DungeonCompasses,
    DungeonMaps,
    ObtainedSeasons,
    BoomerangLevel,
    MagnetGlovePolarity,
    SlingshotLevel,
    FeatherLevel,
    SatchelSelectedSeeds,
    ShooterSelectedSeeds,
    SlingshotSelectedSeeds
}
