using System.Collections.Generic;

namespace oracleofages;

// Session-scoped imported data. Keep first-use caching and staged preparation
// here; placement and actor construction consume the same database instances.
internal sealed class RoomEntityResources(RoomSession? rooms)
{
    private KeyholeControllerDatabase? _keyholeControllers;
    internal KeyholeControllerDatabase KeyholeControllers => _keyholeControllers ??= new();
    // Factory construction must not parse assets for every later dungeon and
    // story actor. Resolve each per-session database at its first dispatch;
    // room-wide gates below still resolve their inputs in the original order.
    private VolcanoDatabase? _volcanoData;
    internal VolcanoDatabase Volcano => _volcanoData ??= new();
    private FallingBoulderDatabase? _fallingBouldersData;
    internal FallingBoulderDatabase FallingBoulders => _fallingBouldersData ??= new();
    private ZoraFireDatabase? _zoraFireData;
    internal ZoraFireDatabase ZoraFire => _zoraFireData ??= new();
    private BeamosBeamDatabase? _beamosBeamData;
    internal BeamosBeamDatabase BeamosBeam => _beamosBeamData ??= new();
    private SmogProjectileDatabase? _smogProjectileData;
    internal SmogProjectileDatabase SmogProjectile => _smogProjectileData ??= new();
    private SmogCollisionDatabase? _smogCollisionsData;
    internal SmogCollisionDatabase SmogCollisions => _smogCollisionsData ??= new();
    private SmogControllerDatabase? _smogControllerData;
    internal SmogControllerDatabase SmogController => _smogControllerData ??= new();
    private SeedShooterEyeStatueDatabase? _eyeStatuesData;
    internal SeedShooterEyeStatueDatabase EyeStatues => _eyeStatuesData ??= new();
    private DungeonChestPatternDatabase? _chestPatternsData;
    internal DungeonChestPatternDatabase ChestPatterns => _chestPatternsData ??= new();
    private SpikedBallDatabase? _spikedBallData;
    internal SpikedBallDatabase SpikedBall => _spikedBallData ??= new();
    private FountainFairyDatabase? _fountainFairiesData;
    internal FountainFairyDatabase FountainFairies => _fountainFairiesData ??= new();
    private WaterfallWarpDatabase? _waterfallWarpsData;
    internal WaterfallWarpDatabase WaterfallWarps => _waterfallWarpsData ??= new();
    private WaterPushblockDatabase? _waterPushblocksData;
    internal WaterPushblockDatabase WaterPushblocks => _waterPushblocksData ??= new();
    private CarpenterDatabase? _carpentersData;
    internal CarpenterDatabase Carpenters => _carpentersData ??= new();
    private SymmetryDatabase? _symmetryData;
    internal SymmetryDatabase Symmetry => _symmetryData ??= new();
    private PatchDatabase? _patchData;
    internal PatchDatabase Patch => _patchData ??= new();
    private TuniNutDatabase? _tuniNutData;
    internal TuniNutDatabase TuniNut => _tuniNutData ??= new();
    private Room148PickaxeDatabase? _room148Data;
    internal Room148PickaxeDatabase Room148 => _room148Data ??= new();
    private Room149FamilyDatabase? _room149Data;
    internal Room149FamilyDatabase Room149 => _room149Data ??= new();
    private MakuSproutRoomDatabase? _makuSproutRoomData;
    internal MakuSproutRoomDatabase MakuSproutRoom => _makuSproutRoomData ??= new();
    private KnowItAllBirdDatabase? _knowItAllBirds;
    internal KnowItAllBirdDatabase KnowItAllBirds => _knowItAllBirds ??= new();
    private Room20eNpcDatabase? _room20eData;
    internal Room20eNpcDatabase Room20e => _room20eData ??= new();
    private Room2e3Database? _room2e3Data;
    internal Room2e3Database Room2e3 => _room2e3Data ??= new();
    private Room5b6Database? _room5b6Data;
    internal Room5b6Database Room5b6 => _room5b6Data ??= new();
    private Room5bfDatabase? _room5bfData;
    internal Room5bfDatabase Room5bf => _room5bfData ??= new();
    private StoneRabbitDatabase? _stoneRabbitData;
    internal StoneRabbitDatabase StoneRabbit => _stoneRabbitData ??= new();
    private BusinessScrubDatabase? _businessScrubData;
    internal BusinessScrubDatabase BusinessScrub => _businessScrubData ??= new();
    private NayruHouseDatabase? _nayruHouseData;
    internal NayruHouseDatabase NayruHouse => _nayruHouseData ??= new();
    private VasuShopDatabase? _vasuShopData;
    internal VasuShopDatabase VasuShop => _vasuShopData ??= new();
    private LynnaShopDatabase? _lynnaShopData;
    internal LynnaShopDatabase LynnaShop => _lynnaShopData ??= new();
    private LynnaShopDatabase? _hiddenShopData;
    internal LynnaShopDatabase HiddenShop => _hiddenShopData ??= new(hidden: true);
    private TokayInteractionDatabase? _tokayInteractionsData;
    internal TokayInteractionDatabase TokayInteractions => _tokayInteractionsData ??= new();
    private TokayNativeDatabase? _tokayNativeData;
    internal TokayNativeDatabase TokayNative => _tokayNativeData ??= new();
    private TokaySeedlingPlotDatabase? _tokaySeedlingPlotData;
    private FountainDatabase? _fountainData;
    internal FountainDatabase Fountains => _fountainData ??= new();
    internal TokaySeedlingPlotDatabase TokaySeedlingPlot => _tokaySeedlingPlotData ??= new();
    private TokayShopDatabase? _tokayShopData;
    internal TokayShopDatabase TokayShop => _tokayShopData ??= new();
    private WildTokayMeatDatabase? _wildTokayMeatData;
    internal WildTokayMeatDatabase WildTokayMeat => _wildTokayMeatData ??= new();
    private TokayEntranceEyeDatabase? _tokayEntranceEyesData;
    internal TokayEntranceEyeDatabase TokayEntranceEyes => _tokayEntranceEyesData ??= new();
    private BlackTowerWorkerDatabase? _blackTowerData;
    internal BlackTowerWorkerDatabase BlackTower => _blackTowerData ??= new();
    private ShootingGalleryEventDatabase? _shootingGalleryData;
    internal ShootingGalleryEventDatabase ShootingGallery => _shootingGalleryData ??= new();
    private ComedianEventDatabase? _comedianData;
    internal ComedianEventDatabase Comedian => _comedianData ??= new();
    private MaskSalesmanEventDatabase? _maskSalesmanData;
    internal MaskSalesmanEventDatabase MaskSalesman => _maskSalesmanData ??= new();
    private DumbbellManEventDatabase? _dumbbellManData;
    internal DumbbellManEventDatabase DumbbellMan => _dumbbellManData ??= new();
    private ChevalEventDatabase? _chevalData;
    internal ChevalEventDatabase Cheval => _chevalData ??= new();
    private RalphAfterChevalEventDatabase? _ralphAfterChevalData;
    internal RalphAfterChevalEventDatabase RalphAfterCheval => _ralphAfterChevalData ??= new();
    private RalphAfterRaftonEventDatabase? _ralphAfterRaftonData;
    internal RalphAfterRaftonEventDatabase RalphAfterRafton => _ralphAfterRaftonData ??= new();
    private RaftonEventDatabase? _raftonData;
    internal RaftonEventDatabase Rafton => _raftonData ??= new();
    private RaftDatabase? _raftData;
    internal RaftDatabase Raft => _raftData ??= new();
    private DepressedBoyEventDatabase? _depressedBoyData;
    internal DepressedBoyEventDatabase DepressedBoy => _depressedBoyData ??= new();
    private ToiletHandEventDatabase? _toiletHandData;
    internal ToiletHandEventDatabase ToiletHand => _toiletHandData ??= new();
    private PoeEventDatabase? _poeData;
    internal PoeEventDatabase Poe => _poeData ??= new();
    private TroyHouseDatabase? _troyHouseData;
    internal TroyHouseDatabase TroyHouse => _troyHouseData ??= new();
    private DungeonEntranceInteractionDatabase? _dungeonEntrancesData;
    internal DungeonEntranceInteractionDatabase DungeonEntrances => _dungeonEntrancesData ??= new();
    private DungeonInteractionDatabase? _dungeonInteractionsData;
    internal DungeonInteractionDatabase DungeonInteractions => _dungeonInteractionsData ??= new();
    private DungeonInteractionVisualDatabase? _dungeonVisualsData;
    internal DungeonInteractionVisualDatabase DungeonVisuals => _dungeonVisualsData ??= new();
    private DungeonSpinnerDatabase? _dungeonSpinnersData;
    internal DungeonSpinnerDatabase DungeonSpinners => _dungeonSpinnersData ??= new();
    private DungeonBossDatabase? _dungeonBossesData;
    internal DungeonBossDatabase DungeonBosses => _dungeonBossesData ??= new();
    private SpiritsGraveDatabase? _spiritsGraveData;
    internal SpiritsGraveDatabase SpiritsGrave => _spiritsGraveData ??= new();
    private WingDungeonDatabase? _wingDungeonData;
    internal WingDungeonDatabase WingDungeon => _wingDungeonData ??= new();
    private MoonlitGrottoDatabase? _moonlitGrottoData;
    internal MoonlitGrottoDatabase MoonlitGrotto => _moonlitGrottoData ??= new();
    private SkullDungeonDatabase? _skullDungeonData;
    internal SkullDungeonDatabase SkullDungeon => _skullDungeonData ??= new();
    private CrownDungeonDatabase? _crownDungeonData;
    internal CrownDungeonDatabase CrownDungeon => _crownDungeonData ??= new();
    private PushBlockSynchronizerDatabase? _pushSynchronizersData;
    internal PushBlockSynchronizerDatabase PushSynchronizers => _pushSynchronizersData ??= new();
    private PuzzleTrapResetDatabase? _trapResetsData;
    internal PuzzleTrapResetDatabase TrapResets => _trapResetsData ??= new();
    private ArmosWarriorDatabase? _armosWarriorData;
    internal ArmosWarriorDatabase ArmosWarrior => _armosWarriorData ??= new();
    private KingMoblinDatabase? _kingMoblinData;
    internal KingMoblinDatabase KingMoblin => _kingMoblinData ??= new();
    private EyesoarDatabase? _eyesoarData;
    internal EyesoarDatabase Eyesoar => _eyesoarData ??= new();
    private LeverDatabase? _leversData;
    internal LeverDatabase Levers => _leversData ??= new();
    private LeverLavaDatabase? _leverLavaData;
    internal LeverLavaDatabase LeverLava => _leverLavaData ??= new();
    private MovingPlatformDatabase? _movingPlatformsData;
    internal MovingPlatformDatabase MovingPlatforms => _movingPlatformsData ??= new();
    private StaticDungeonObjectDatabase? _staticDungeonObjectsData;
    internal StaticDungeonObjectDatabase StaticDungeonObjects => _staticDungeonObjectsData ??= new();
    private MovingSideScrollPlatformDatabase? _sidePlatformsData;
    internal MovingSideScrollPlatformDatabase SidePlatforms => _sidePlatformsData ??= new();
    private EnemySpawnTileDatabase? _enemySpawnTilesData;
    internal EnemySpawnTileDatabase EnemySpawnTiles => _enemySpawnTilesData ??= new();
    private GroundTreasureDatabase? _groundTreasuresData;
    internal GroundTreasureDatabase GroundTreasures => _groundTreasuresData ??= new();
    private DungeonMechanicDatabase? _dungeonMechanicsData;
    internal DungeonMechanicDatabase DungeonMechanics => _dungeonMechanicsData ??= new();
    private RoomTileChangeWatcherDatabase? _tileChangeWatchersData;
    internal RoomTileChangeWatcherDatabase TileChangeWatchers => _tileChangeWatchersData ??= new();
    private CollapsingFloorDatabase? _collapsingFloorsData;
    internal CollapsingFloorDatabase CollapsingFloors => _collapsingFloorsData ??= new();
    private BreakableTileDatabase? _breakablesData;
    internal BreakableTileDatabase Breakables => _breakablesData ??= new();
    private LedgeJumpDatabase? _ledgeJumpsData;
    internal LedgeJumpDatabase LedgeJumps => _ledgeJumpsData ??= new();
    private SwordBeamDatabase? _swordBeamData;
    internal SwordBeamDatabase SwordBeam => _swordBeamData ??= new();
    private BraceletDatabase? _braceletData;
    internal BraceletDatabase Bracelet => _braceletData ??= new();
    private BombDatabase? _bombData;
    internal BombDatabase Bomb => _bombData ??= new();
    private GashaSpotDatabase? _gashaSpotsData;
    internal GashaSpotDatabase GashaSpots => _gashaSpotsData ??= new();
    private DarkRoomDatabase? _darkRoomsData;
    internal DarkRoomDatabase DarkRooms => _darkRoomsData ??= new();
    private MapleEventDatabase? _mapleData;
    internal MapleEventDatabase Maple => _mapleData ??= new();
    private SeedTreeDatabase? _seedTreesData;
    internal SeedTreeDatabase SeedTrees => _seedTreesData ??= new();
    private OwlStatueDatabase? _owlStatuesData;
    internal OwlStatueDatabase OwlStatues => _owlStatuesData ??= new();
    private RickyGlovesEventDatabase? _rickyData;
    internal RickyGlovesEventDatabase Ricky => _rickyData ??= new();
    private MooshRescueEventDatabase? _mooshData;
    internal MooshRescueEventDatabase Moosh => _mooshData ??= new();
    private MooshGoodbyeEventDatabase? _mooshGoodbyeData;
    internal MooshGoodbyeEventDatabase MooshGoodbye => _mooshGoodbyeData ??= new();
    private DimitriDatabase? _dimitriData;
    internal DimitriDatabase Dimitri => _dimitriData ??= new();
    private CompanionTutorialDatabase? _companionTutorialsData;
    internal CompanionTutorialDatabase CompanionTutorials => _companionTutorialsData ??= new();
    private CompanionBarrierDatabase? _companionBarriersData;
    internal CompanionBarrierDatabase CompanionBarriers => _companionBarriersData ??= new();
    private TingleDatabase? _tingleData;
    internal TingleDatabase Tingle => _tingleData ??= new();
    internal readonly DungeonMapDatabase DungeonMaps =
        rooms?.DungeonMaps ?? new DungeonMapDatabase();

    internal IEnumerable<bool> PrepareResources()
    {
        _ = Volcano;
        yield return false;
        _ = FallingBoulders;
        yield return false;
        _ = ZoraFire;
        yield return false;
        _ = BeamosBeam;
        yield return false;
        _ = SmogProjectile;
        yield return false;
        _ = SmogCollisions;
        yield return false;
        _ = SmogController;
        yield return false;
        _ = EyeStatues;
        yield return false;
        _ = ChestPatterns;
        yield return false;
        _ = SpikedBall;
        yield return false;
        _ = FountainFairies;
        yield return false;
        _ = WaterfallWarps;
        yield return false;
        _ = WaterPushblocks;
        yield return false;
        _ = Carpenters;
        yield return false;
        _ = Symmetry;
        yield return false;
        _ = Patch;
        yield return false;
        _ = TuniNut;
        yield return false;
        _ = Room148;
        yield return false;
        _ = Room149;
        yield return false;
        _ = MakuSproutRoom;
        yield return false;
        _ = Room20e;
        yield return false;
        _ = Room2e3;
        yield return false;
        _ = Room5b6;
        yield return false;
        _ = Room5bf;
        yield return false;
        _ = StoneRabbit;
        yield return false;
        _ = BusinessScrub;
        yield return false;
        _ = NayruHouse;
        yield return false;
        _ = VasuShop;
        yield return false;
        _ = LynnaShop;
        yield return false;
        _ = HiddenShop;
        yield return false;
        _ = TokayInteractions;
        yield return false;
        _ = TokayNative;
        yield return false;
        _ = TokaySeedlingPlot;
        yield return false;
        _ = TokayShop;
        yield return false;
        _ = WildTokayMeat;
        yield return false;
        _ = TokayEntranceEyes;
        yield return false;
        _ = BlackTower;
        yield return false;
        _ = ShootingGallery;
        yield return false;
        _ = Comedian;
        yield return false;
        _ = MaskSalesman;
        yield return false;
        _ = DumbbellMan;
        yield return false;
        _ = Cheval;
        yield return false;
        _ = RalphAfterCheval;
        yield return false;
        _ = RalphAfterRafton;
        yield return false;
        _ = Rafton;
        yield return false;
        _ = Raft;
        yield return false;
        _ = DepressedBoy;
        yield return false;
        _ = ToiletHand;
        yield return false;
        _ = Poe;
        yield return false;
        _ = TroyHouse;
        yield return false;
        _ = DungeonEntrances;
        yield return false;
        _ = DungeonInteractions;
        yield return false;
        _ = DungeonVisuals;
        yield return false;
        _ = DungeonSpinners;
        yield return false;
        _ = DungeonBosses;
        yield return false;
        _ = SpiritsGrave;
        yield return false;
        _ = WingDungeon;
        yield return false;
        _ = MoonlitGrotto;
        yield return false;
        _ = SkullDungeon;
        yield return false;
        _ = CrownDungeon;
        yield return false;
        _ = PushSynchronizers;
        yield return false;
        _ = TrapResets;
        yield return false;
        _ = ArmosWarrior;
        yield return false;
        _ = KingMoblin;
        yield return false;
        _ = Eyesoar;
        yield return false;
        _ = Levers;
        yield return false;
        _ = LeverLava;
        yield return false;
        _ = MovingPlatforms;
        yield return false;
        _ = StaticDungeonObjects;
        yield return false;
        _ = SidePlatforms;
        yield return false;
        _ = EnemySpawnTiles;
        yield return false;
        _ = GroundTreasures;
        yield return false;
        _ = DungeonMechanics;
        yield return false;
        _ = TileChangeWatchers;
        yield return false;
        _ = CollapsingFloors;
        yield return false;
        _ = Breakables;
        yield return false;
        _ = LedgeJumps;
        yield return false;
        _ = SwordBeam;
        yield return false;
        _ = Bracelet;
        yield return false;
        _ = Bomb;
        yield return false;
        _ = GashaSpots;
        yield return false;
        _ = DarkRooms;
        yield return false;
        _ = Maple;
        yield return false;
        _ = SeedTrees;
        yield return false;
        _ = OwlStatues;
        yield return false;
        _ = Ricky;
        yield return false;
        _ = Moosh;
        yield return false;
        _ = MooshGoodbye;
        yield return false;
        _ = Dimitri;
        yield return false;
        _ = CompanionTutorials;
        yield return false;
        _ = CompanionBarriers;
        yield return false;
        _ = Tingle;
        yield return false;
    }

}
